// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://msrajpxxrczejxqvwcxl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zcmFqcHh4cmN6ZWp4cXZ3Y3hsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NDQ0MDYsImV4cCI6MjA3MjEyMDQwNn0.y39UaCqUQSkAzKJX3V543ogXlTSNurATt6eui6yrHg4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});